
let studies=[],topics=[],verses={},currentStudy=null,currentTopic=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function init(){studies=await (await fetch('data/studies.json',{cache:'no-store'})).json();topics=await (await fetch('data/topics.json',{cache:'no-store'})).json();verses=await (await fetch('data/verses.json',{cache:'no-store'})).json();renderLibrary();bind();showLibrary()}
function closeSide(){$('#sidebar').classList.remove('open')}
function showLibrary(){$('#libraryView').hidden=false;$('#studyView').hidden=true;$('#topicView').hidden=true;currentStudy=null;$('#brandTitle').textContent='Bible Study Library';renderSideStudies();closeSide();window.scrollTo(0,0)}
function showStudy(){$('#libraryView').hidden=true;$('#studyView').hidden=false;$('#topicView').hidden=true;$('#brandTitle').textContent=currentStudy.title;renderTopicIndex();closeSide();window.scrollTo(0,0)}
function showTopic(){$('#libraryView').hidden=true;$('#studyView').hidden=true;$('#topicView').hidden=false;$('#brandTitle').textContent=currentStudy.title;renderTopic();closeSide();window.scrollTo(0,0)}
function renderLibrary(){$('#studyCards').innerHTML=studies.map(s=>`<article class="studyCard"><div class="studyThumb">${s.icon}</div><h3>${s.title}</h3><p><b>${s.subtitle}</b></p><p>${s.description}</p><button data-study="${s.id}">Open Study →</button></article>`).join('');$$('[data-study]').forEach(b=>b.onclick=()=>openStudy(b.dataset.study))}
function renderSideStudies(q=''){$('#sideHeading').textContent='Studies';let m=studies.filter(s=>(s.title+' '+s.subtitle).toLowerCase().includes(q.toLowerCase()));$('#sideNav').innerHTML=m.map(s=>`<button data-study="${s.id}">${s.icon} ${s.title}<small>${s.subtitle}</small></button>`).join('');$$('#sideNav [data-study]').forEach(b=>b.onclick=()=>openStudy(b.dataset.study))}
function openStudy(id){currentStudy=studies.find(s=>s.id===id);$('#studyTitle').textContent=currentStudy.title;$('#studyDescription').textContent=currentStudy.description;$('#studyCrumb').textContent=currentStudy.title;$('#crumbStudy').textContent=currentStudy.title;showStudy()}
function renderTopicIndex(q=''){$('#sideHeading').textContent='Study Index';let m=topics.filter(t=>(t.title+' '+t.subtitle+' '+t.verses.join(' ')).toLowerCase().includes(q.toLowerCase()));$('#sideNav').innerHTML=m.map(t=>`<button data-topic="${t.id}"><b>${topics.indexOf(t)+1}. ${t.title}</b><small>${t.subtitle}</small></button>`).join('');$('#topicCards').innerHTML=m.map(t=>`<button class="topicCard" data-topic="${t.id}"><h3>${topics.indexOf(t)+1}. ${t.title}</h3><p>${t.subtitle}</p></button>`).join('');$$('[data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic))}
function openTopic(id){currentTopic=topics.findIndex(t=>t.id===id);showTopic()}
function renderTopic(){let t=topics[currentTopic];$('#topicNumber').textContent=currentTopic+1;$('#topicTitle').textContent=t.title;$('#topicRefs').textContent=t.verses.join('   |   ');$('#crumbTopic').textContent=t.title;$('#preSummary').textContent=t.pretrib.summary;$('#sdaSummary').textContent=t.adventist.summary;$('#bibleFirst').textContent=t.bible_first;$('#featuredVerse').textContent=verses[t.verses[0]]||t.verses[0];$('#takeawayList').innerHTML=t.takeaways.map(x=>`<li>${x}</li>`).join('');$('#relatedList').innerHTML=topics.filter((_,i)=>i!==currentTopic).slice(0,4).map(r=>`<button data-related="${r.id}">${r.title} ›</button>`).join('');$$('[data-related]').forEach(b=>b.onclick=()=>openTopic(b.dataset.related));$('#sideHeading').textContent='Study Index';$('#sideNav').innerHTML=topics.map((x,i)=>`<button class="${i===currentTopic?'active':''}" data-topic="${x.id}">${i+1}. ${x.title}<small>${x.subtitle}</small></button>`).join('');$$('#sideNav [data-topic]').forEach(b=>b.onclick=()=>openTopic(b.dataset.topic));$('#prevBtn').disabled=currentTopic===0;$('#nextBtn').disabled=currentTopic===topics.length-1}
function detail(k){let t=topics[currentTopic],title='',html='';if(k==='preTeach'){title='Christian Pre-Tribulation — Their Teachings';html=`<p>${t.pretrib.teaching}</p>`}if(k==='sdaTeach'){title='Seventh-day Adventist — Their Teachings';html=`<p>${t.adventist.teaching}</p>`}if(k==='preSupport'){title='Christian Pre-Tribulation — Bible Support';html=support(t.pretrib.support)}if(k==='sdaSupport'){title='Seventh-day Adventist — Bible Support';html=support(t.adventist.support)}openDialog(title,html)}
function support(items){return items.map(x=>`<div class="supportItem"><button data-ref="${x.ref}">📖 ${x.ref}</button><p>${x.why}</p></div>`).join('')}
function openDialog(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;$$('#dialogBody [data-ref]').forEach(b=>b.onclick=()=>showVerse(b.dataset.ref));$('#dialog').showModal()}
function showVerse(ref){openDialog(ref,`<p style="font-family:Georgia,serif;font-size:19px;line-height:1.6">${verses[ref]||'Verse text not added yet.'}</p>`)}
function bind(){$('#menuBtn').onclick=()=>$('#sidebar').classList.add('open');$('#closeSide').onclick=closeSide;$('#homeBtn').onclick=$('#backLibrary').onclick=$('#crumbHome').onclick=showLibrary;$('#crumbStudy').onclick=showStudy;$('#aboutBtn').onclick=()=>openDialog('About','<p>This is a growing Bible Study Library. Each study has its own index and comparison pages.</p>');$('#settingsBtn').onclick=()=>openDialog('Settings','<p>More settings can be added later.</p>');$('#search').oninput=e=>currentStudy?renderTopicIndex(e.target.value):renderSideStudies(e.target.value);$$('[data-action]').forEach(b=>b.onclick=()=>detail(b.dataset.action));$('#closeDialog').onclick=()=>$('#dialog').close();$('#readPassage').onclick=()=>{let t=topics[currentTopic];openDialog('Read Full Passage',t.verses.map(r=>`<div class="supportItem"><button data-ref="${r}">📖 ${r}</button><p>${verses[r]||''}</p></div>`).join(''))};$('#keyObs').onclick=()=>openDialog('Key Observations',`<p>${topics[currentTopic].bible_first}</p>`);$('#prevBtn').onclick=()=>{if(currentTopic>0){currentTopic--;showTopic()}};$('#nextBtn').onclick=()=>{if(currentTopic<topics.length-1){currentTopic++;showTopic()}}}
init();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
